Itay&Herman - Elevator!!
GreenBlitz/FTC-CENTERSTAGE pull request #14
Opened 2024-06-15 09:22 UTC by YHerm

Before issuing a pull request, please see the contributing page.

2024-06-15 10:03 UTC, hillelv commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/elevator/ElevatorCommands.java
> +                () -> false,
Maybe triggerValue.get() < TOLERANCE instead?

2024-06-15 10:10 UTC, hillelv commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot.java
> +    public Elevator elevator;
![image](https://github.com/GreenBlitz/FTC-CENTERSTAGE/assets/140002343/5ab21f37-38b1-401e-90c2-47989839bc0b)

2024-06-15 12:26 UTC, tnrz135 requested changes

2024-06-15 12:26 UTC, tnrz135 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Bindings.java
> +        // Human Control
Try using seperate functions to avoid having to document your code

2024-06-15 12:26 UTC, tnrz135 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot.java
>      //add subsystems...
Very important.

2024-06-15 12:26 UTC, tnrz135 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmodes/testers/RazElevatorTest.java
> +        // todo - add telemetry
Do not leave todo in PR

2024-06-15 12:26 UTC, tnrz135 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/elevator/Elevator.java
> +    // todo - telemetry
Again, don't leave todo is the PR.
Also, telemetry is very important for testing and finding out bugs, this shouldn't be left over, at least until you become a BOP programmer.

2024-06-15 12:26 UTC, tnrz135 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/elevator/ElevatorCommands.java
> +public class ElevatorCommands {
Consider splitting the commands to seperate files

2024-06-15 12:26 UTC, tnrz135 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/elevator/ElevatorCommands.java
> +    public static Command humanControl(Supplier<Double> triggerValue) { //todo- ask herman to explain Supplier and generic object
TODO: Delete this todo.

2024-06-15 12:26 UTC, tnrz135 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/elevator/ElevatorConstants.java
> +public class ElevatorConstants {
Finshing working on a feature means doing the entire work, not just writing the code. Those additional task in this file should be handled before merging.

2024-06-15 12:35 UTC, ItayKauff commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/elevator/ElevatorCommands.java
> +    public static Command humanControl(Supplier<Double> triggerValue) { //todo- ask herman to explain Supplier and generic object
you mean
//todo- Delete this todo

2024-06-16 05:53 UTC, tnrz135 approved these changes

2024-06-16 06:05 UTC, merged