Wrist
GreenBlitz/FTC-CENTERSTAGE pull request #8
Opened 2024-06-13 21:02 UTC by DANNA2828

Not checked on robot yet.

2024-06-13 21:47 UTC, YHerm commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/Wrist.java
> +    public WristState currentState;
the state need to be private

2024-06-13 21:47 UTC, YHerm commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/WristCommands.java
> +
remove space

2024-06-13 21:47 UTC, YHerm commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/WristConstants.java
> +}
add space before last line

2024-06-13 21:47 UTC, YHerm commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/WristCommands.java
> +                interrupt -> Robot.getInstance().WRIST.stop(),
do you really want to stop at the end? why not keep aiming to target all the time?

2024-06-13 21:47 UTC, YHerm commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/WristConstants.java
> +    public static double POSITION_TOLERANCE_DEGREES = 5;
go again on the values of these constants please

2024-06-14 14:29 UTC, ItayKauff requested changes

2024-06-14 14:29 UTC, ItayKauff commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/Wrist.java
>  public class Wrist extends SubsystemBase {
what does it get from SubsystemBase? why does it need to inherit it?

2024-06-14 14:29 UTC, ItayKauff commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/Wrist.java
> +        wristServo.setPosition(currentState.positionZeroToOne);
I would've created a setPosition function in Wrist so we wouldn't need to access the servo wristServo and only the Wrist class

2024-06-14 14:29 UTC, ItayKauff commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/WristConstants.java
> +    public static double SCORE_POSITION = 0.5;
את אתמול:
erm..
i will just use the servo programmer to make it 1 and 0🤓☝

2024-06-14 14:29 UTC, ItayKauff commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/Wrist.java
> +        wristServo.setPosition(wristServo.getPosition());
cursed but i likey

2024-06-14 14:29 UTC, ItayKauff commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/WristState.java
> +    public final double positionZeroToOne;
לא אינדיקטיבי לגביי מה שזה עושה

2024-06-14 15:04 UTC, ItayKauff requested changes

2024-06-14 15:04 UTC, ItayKauff commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/WristState.java
> +    public final double targetPosition;
i now understand what it means and i likey

2024-06-14 15:04 UTC, ItayKauff commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/Wrist.java
> +        this.wristServo = hardwareMap.servo.get(WristConstants.SERVO_HARDWARE_NAME);
add
currentState = <>;
and decide what will be the reset position

2024-06-14 15:04 UTC, ItayKauff commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/Wrist.java
> +        this.wristServo = hardwareMap.servo.get(WristConstants.SERVO_HARDWARE_NAME);
so when the object constructs you will know what is the currentState

2024-06-14 16:04 UTC, hillelv reviewed
very nice - just delete unused imports and ctrl alt L

2024-06-14 16:27 UTC, YHerm commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmodes/testers/WristTest.java
> +public class WristTest extends DefaultRaz {
```suggestion
@TeleOp(name = "Raz Wrist Test")
public class RazWristTest extends DefaultRaz {
```

2024-06-14 16:27 UTC, YHerm commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmodes/testers/WristTest.java
> +        Bindings.wristBindings(gamepad1, gamepad2);
```suggestion
        Bindings.razWristTestBindings(gamepad1, gamepad2);
```

2024-06-14 16:27 UTC, YHerm commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/Wrist.java
> +    }
consider adding current position

2024-06-14 16:28 UTC, YHerm reviewed
KEEP THE CONVENTION!!!

2024-06-14 16:46 UTC, YHerm reviewed
Merge master to you, ctrl alt l and remove unused imports

2024-06-14 16:46 UTC, YHerm commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Bindings.java
> +    public static void wristBindings(Gamepad gamepad1, Gamepad gamepad2){
```suggestion
    public static void razWristTestBindings(Gamepad gamepad1, Gamepad gamepad2){
```

2024-06-14 16:46 UTC, YHerm commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/Wrist.java
> +    private WristState currentTargetState;
consider changing the name, current or target state?

2024-06-14 16:46 UTC, YHerm commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/Wrist.java
> +    public void setState(WristState state){
can be protected

2024-06-14 16:46 UTC, YHerm commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/Wrist.java
> +        telemetry.addData("Wrist isAtTargetState?:", isAtTargetState(currentTargetState));
```suggestion
        telemetry.addData("Wrist isAtTargetState:", isAtTargetState(currentTargetState));
```

2024-06-14 16:50 UTC, YHerm commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/Wrist.java
> +        telemetry.addData("Wrist TargetState:", currentTargetState);
```suggestion
        telemetry.addData("Wrist TargetState: ", currentTargetState);
```

2024-06-14 19:55 UTC, YHerm commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/Wrist.java
> +    private final Servo wristServo;
you're in wrist class so consider renaming to just servo

2024-06-16 08:18 UTC, greenblitz4590 reviewed
merge master to you

2024-06-16 08:18 UTC, greenblitz4590 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot.java
> +    public Wrist WRIST;
add get and make private

2024-06-16 08:18 UTC, greenblitz4590 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/Wrist.java
> +        currentTargetState = WristState.INTAKE;
this.

2024-06-16 08:47 UTC, greenblitz4590 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmodes/testers/RazWristTest.java
> +public class RazWristTest extends DefaultRaz {
```suggestion
@TeleOp(name = "Raz Wrist Test")
public class RazWristTest extends DefaultRaz {
```

2024-06-16 08:48 UTC, greenblitz4590 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/WristConstants.java
> +public class WristConstants {
make protected

2024-06-16 08:48 UTC, greenblitz4590 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/WristConstants.java
> +    public static double POSITION_TOLERANCE = 0.07;
make protected

2024-06-16 09:00 UTC, greenblitz4590 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Robot.java
> +    private Wrist WRIST;
make small

2024-06-16 09:01 UTC, greenblitz4590 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/opmodes/testers/RazWristTest.java
> +public class RazWristTest extends DefaultRaz {
line space

2024-06-16 09:01 UTC, greenblitz4590 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/WristCommands.java
> +    public static FunctionalCommand moveToStateCommand(WristState state){
```suggestion
    public static FunctionalCommand moveToState(WristState state){
```

2024-06-16 09:03 UTC, greenblitz4590 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/Wrist.java
> +    }
```suggestion
    public boolean isAtTargetState(WristState targetState){
        return targetState.ticks == getPosition()
    }
```

2024-06-16 09:04 UTC, greenblitz4590 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/WristCommands.java
> +    }
make instant command

2024-06-16 09:04 UTC, greenblitz4590 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/WristConstants.java
> +    static double POSITION_TOLERANCE = 0.07;
remove

2024-06-16 09:21 UTC, greenblitz4590 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/WristCommands.java
> +    public static InstantCommand moveToState(WristState state){
require

2024-06-16 09:21 UTC, greenblitz4590 commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/WristConstants.java
> +    static double SCORE_POSITION = 0;
protected

2024-06-16 12:55 UTC, hillelv commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/WristCommands.java
> +    public static InstantCommand moveToState(WristState state){
```suggestion
    public static Command moveToState(WristState state){
```

2024-06-16 12:55 UTC, hillelv commented on TeamCode/src/main/java/org/firstinspires/ftc/teamcode/subsystems/wrist/WristConstants.java
> +    protected static String SERVO_HARDWARE_NAME = "wrist_gripper";
```suggestion
    protected static String SERVO_HARDWARE_ID = "wrist_gripper";
```

2024-06-16 13:52 UTC, greenblitz4590 approved these changes

2024-06-16 14:09 UTC, ItayKauff approved these changes

2024-06-16 14:09 UTC, merged